version: '3.8'

services:
  web:
    build: .
    container_name: globant_flask_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Alex@Globant2023*
      - DATABASE_DB=globant_flask_db
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: ["python", "/app/app.py"]

  db:
    image: mariadb:latest
    container_name: globant_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Alex@Globant2023*
      - MYSQL_DATABASE=globant_flask_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
